import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import AuthProvider from "./components/AuthProvider";
import Link from "next/link";
import { supabase } from "@/lib/supabaseClient";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// ------------------------------
// 🟦 Botón Login / Logout (Server Component)
// ------------------------------
async function AuthButton() {
  const { data } = await supabase.auth.getSession();
  const session = data.session;

  // Si NO está logueado → mostrar botón login
  if (!session) {
    return (
      <div className="absolute top-4 right-4">
        <Link
          href="/login"
          className="px-4 py-2 rounded-lg bg-blue-600 text-white hover:bg-blue-700 transition"
        >
          Login
        </Link>
      </div>
    );
  }

  // Si está logueado → mostrar logout server action
  async function logout() {
    "use server";
    await supabase.auth.signOut();
  }

  return (
    <div className="absolute top-4 right-4">
      <form action={logout}>
        <button
          type="submit"
          className="px-4 py-2 rounded-lg bg-red-600 text-white hover:bg-red-700 transition"
        >
          Logout
        </button>
      </form>
    </div>
  );
}

// ------------------------------
// 🟦 Root Layout
// ------------------------------
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* Botón Login / Logout siempre visible */}
        <AuthButton />

        {/* Proveedor de sesión */}
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
